use_frameworks!

platform :ios, '9.0'

target 'IDAdSDK_Example' do
  
  pod 'IDAdSDK', :path => '../'
  #pod 'KSAdSDK',:path => './KSAdSDK/'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'Masonry'
  pod 'SDWebImage', '5.9.4'

  target 'IDAdSDK_Tests' do
    inherit! :search_paths

    
  end
end
